### ISSUE TITLE
Crash on fastlane execution

### ISSUE THREAD

**Issue by mikhail-shekhtman** [bitrise-steplib/steps-fastlane#106]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.5.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/) this  page is not found
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Build stopped working wihtout any changes in the stack. In attemnpts to fix this behavior I updated fastlane itself from 2.211.0 -> 2.219.0

### Bitrise info

- Build URL:  https://app.bitrise.io/build/c885631a-ef70-48fd-abb1-3b4cc0623348
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
 fastlane installation at path:
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/fastlane-2.219.0/bin/fastlane
-----------------------------
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]
-- Control frame information -----------------------------------------------
c:0012 p:---- s:0057 e:000056 CFUNC  :to_s
c:0011 p:---- s:0054 e:000053 CFUNC  :to_str
c:0010 p:---- s:0051 e:000050 CFUNC  :to_s
c:0009 p:---- s:0048 e:000047 CFUNC  :message
c:0008 p:0040 s:0044 e:000035 METHOD /root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96
c:0007 p:0129 s:0031 e:000030 METHOD /root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:50
c:0006 p:0040 s:0026 e:000025 RESCUE /root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:134
c:0005 p:0008 s:0022 e:000021 METHOD /root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:126
c:0004 p:0096 s:0017 E:001958 TOP    /root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/exe/bundle:37 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0081 s:0008 E:0004b0 EVAL   /root/.asdf/installs/ruby/3.2.1/bin/bundle:25 [FINISH]
c:0001 p:0000 s:0003 E:000370 DUMMY  [FINISH]
-- Ruby level backtrace information ----------------------------------------
/root/.asdf/installs/ruby/3.2.1/bin/bundle:25:in `<main>'
/root/.asdf/installs/ruby/3.2.1/bin/bundle:25:in `load'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/exe/bundle:37:in `<top (required)>'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:126:in `with_friendly_errors'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:134:in `rescue in with_friendly_errors'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:50:in `log_error'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96:in `request_issue_report_for'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96:in `message'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96:in `to_s'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96:in `to_str'
/root/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:96:in `to_s'
-- Machine register context ------------------------------------------------
 RIP: 0x00007fbde79a4644 RBP: 0x0000000000000000 RSP: 0x00007fffae2199d0
 RAX: 0x00007fbde0b1f288 RBX: 0x0000000000000000 RCX: 0x0000000000000000
 RDX: 0x00007fbde0b1f238 RDI: 0x00007fbde0b1f288 RSI: 0x0000000000000000
  R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x0000562b0f2586d0
 R11: 0x0000000000000e11 R12: 0x00007fbde0b1f288 R13: 0x0000000000000000
 R14: 0x000000000000000c R15: 0x0000562b0f16acd0 EFL: 0x0000000000010202
-- C level backtrace information -------------------------------------------
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_print_backtrace+0x11) [0x7fbde7a37704] vm_dump.c:785
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_vm_bugreport) vm_dump.c:1080
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_bug_for_fatal_signal+0xf4) [0x7fbde7830914] error.c:813
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(sigsegv+0x4d) [0x7fbde7989c0d] signal.c:964
/lib/x86_64-linux-gnu/libpthread.so.0(__restore_rt+0x0) [0x7fbde748e420]
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(RB_ENCODING_GET_INLINED+0x0) [0x7fbde79a4644] string.c:1320
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(str_enc_fastpath) string.c:157
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(str_replace_shared_without_enc) string.c:1321
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(RB_FL_TEST_RAW+0x0) [0x7fbde79a79ba] string.c:1364
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(RB_ENCODING_GET_INLINED) ./include/ruby/internal/encoding/encoding.h:100
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(RB_ENCODING_GET) ./include/ruby/internal/encoding/encoding.h:213
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(str_enc_copy) string.c:768
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_enc_cr_str_exact_copy) string.c:804
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(str_replace_shared) string.c:1365
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(str_new_shared) string.c:1372
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_sym_to_s) string.c:11534
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_cfp_consistent_p+0x0) [0x7fbde7a2a30f] vm_eval.c:150
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc_with_frame) vm_eval.c:152
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc) vm_eval.c:164
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_body) vm_eval.c:210
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_funcallv+0x19c) [0x7fbde7a2d91c] vm_eval.c:87
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_obj_as_string+0x23) [0x7fbde79a8763] string.c:1689
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(name_err_mesg_to_str+0x129) [0x7fbde7832769] error.c:2106
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_cfp_consistent_p+0x0) [0x7fbde7a2a30f] vm_eval.c:150
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc_with_frame) vm_eval.c:152
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc) vm_eval.c:164
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_body) vm_eval.c:210
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_vm_call0+0xcf) [0x7fbde7a2ae3f] vm_eval.c:58
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_check_funcall_default_kw+0x1b0) [0x7fbde7a1b170] vm_eval.c:691
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(convert_type_with_id+0xf) [0x7fbde78e7e45] object.c:2975
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_check_convert_type_with_id) object.c:3067
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_String+0xd) [0x7fbde78ea18d] object.c:3741
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_cfp_consistent_p+0x0) [0x7fbde7a2a30f] vm_eval.c:150
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc_with_frame) vm_eval.c:152
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_cfunc) vm_eval.c:164
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call0_body) vm_eval.c:210
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_funcallv+0x19c) [0x7fbde7a2d91c] vm_eval.c:87
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0x128) [0x7fbde7a0c038] vm_insnhelper.c:3268
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_method_each_type+0x79) [0x7fbde7a22769] vm_insnhelper.c:3920
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_method+0xc4) [0x7fbde7a23254] vm_insnhelper.c:4070
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fbde7a1bafc] vm_insnhelper.c:5080
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_exec_core) insns.def:820
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_vm_exec+0xac5) [0x7fbde7a21ed5] vm.c:2383
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(raise_load_if_failed+0x0) [0x7fbde78a5056] load.c:697
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_load_internal) load.c:760
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_f_load) load.c:833
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_cfunc_with_frame+0x128) [0x7fbde7a0c038] vm_insnhelper.c:3268
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_method_each_type+0x79) [0x7fbde7a22769] vm_insnhelper.c:3920
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_call_method+0xc4) [0x7fbde7a23254] vm_insnhelper.c:4070
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_sendish+0x0) [0x7fbde7a1bafc] vm_insnhelper.c:5080
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(vm_exec_core) insns.def:820
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_vm_exec+0xac5) [0x7fbde7a21ed5] vm.c:2383
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(rb_ec_exec_node+0xbb) [0x7fbde7835abb] eval.c:289
/root/.asdf/installs/ruby/3.2.1/lib/libruby.so.3.2(ruby_run_node+0x93) [0x7fbde783bf33] eval.c:330
/root/.asdf/installs/ruby/3.2.1/bin/ruby(rb_main+0x21) [0x562b0ead5187] ./main.c:38
/root/.asdf/installs/ruby/3.2.1/bin/ruby(main) ./main.c:57
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fbde72ac083]
[0x562b0ead51de]
**removed memory map and other system information, github is complaning on amount of character**
Failed to install Step dependencies:
  command failed with exit status -1 (bundle "_2.2.27_" "exec" "fastlane" "--version"):
    check the command's output for details
Failed to install Step dependencies:
  command failed with exit status -1 (bundle "_2.2.27_" "exec" "fastlane" "--version"):
    check the command's output for details
  </pre>
</details>

### Steps to reproduce

Build with fastlane on `linux-docker-android-20.04`

**Comment by mikhail-shekhtman** [comment]
After updating to ruby 3.2.2  and running bundle update build is passing.
